# Generated by Django 6.0.2 on 2026-02-12 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Saloni',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.IntegerField(help_text='Trajanje u minutima')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
            ],
            options={
                'verbose_name_plural': 'Usluge',
                'unique_together': {('salon', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('dostupan', 'Dostupan'), ('zauzet', 'Zauzet'), ('blokiran', 'Blokiran')], default='dostupan', max_length=9)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='salons.salon')),
            ],
            options={
                'verbose_name_plural': 'Time Slots',
                'ordering': ['date', 'begin_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('na čekanju', 'Na čekanju'), ('potvrđeno', 'Potvrđeno'), ('završeno', 'Završeno'), ('otkazano', 'Otkazano'), ('nije se pojavio', 'Nije se pojavio')], default='na čekanju', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='salons.service')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='salons.timeslot')),
            ],
            options={
                'verbose_name_plural': 'Rezervacije',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalonWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('ponedeljak', 'Ponedeljak'), ('utorak', 'Utorak'), ('sreda', 'Sreda'), ('cetvrtak', 'Četvrtak'), ('petak', 'Petak'), ('subota', 'Subota'), ('nedelja', 'Nedelja')], max_length=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='salons.salon')),
            ],
            options={
                'verbose_name_plural': 'Salon Working Hours',
                'ordering': ['salon', 'day'],
                'unique_together': {('salon', 'day')},
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['salon', 'date', 'status'], name='salons_time_salon_i_9687ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('salon', 'date', 'begin_time')},
        ),
    ]
