# Generated by Django 6.0.2 on 2026-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salon_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonworkinghours',
            name='image',
        ),
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(default='img/barber_default.png', upload_to=''),
        ),
    ]
