# Generated by Django 6.0.2 on 2026-02-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_remove_salonworkinghours_image_salon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(default='img/barber_default.jpg', upload_to=''),
        ),
    ]
