# Generated by Django 6.0.2 on 2026-02-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_alter_salon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.salon'),
        ),
    ]
