# Generated by Django 6.0.2 on 2026-02-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_appointment_salon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='salons.salon'),
        ),
    ]
