# Generated by Django 6.0.2 on 2026-02-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_alter_appointment_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
