# Generated by Django 6.0.2 on 2026-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_alter_appointment_id_alter_salon_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('na čekanju', 'Na čekanju'), ('u toku', 'U toku'), ('završeno', 'Završeno'), ('otkazano', 'Otkazano')], default='na čekanju', max_length=15),
        ),
    ]
